version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: test_user # Usuário de teste
      POSTGRES_PASSWORD: test_password # Senha de teste
      POSTGRES_DB: test_database # Nome do banco de dados de teste
    ports:
      - "5432:5432" # Porta padrão do PostgreSQL
    volumes:
      - ./data:/var/lib/postgresql/data # Persistência de dados

volumes:
  postgres_data:
